steps:
- id: go_test 
  name: "gcr.io/cloud-builders/go"
  args: ["test", "hpa"]
  env: ["GOPATH=."]

- id: go_build
  name: "gcr.io/cloud-builders/go"
  args: ["build", "./src/hpa"]
  env: ["GOPATH=."]

  #Building image
- id: Building image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go_hpa:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

#push image
- id: Push image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/go_hpa:$SHORT_SHA']

#adjusting file k8s
- id: Adjusting file k8s
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args: 
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/go_hpa:$SHORT_SHA#g' k8s/app-deployment.yaml > k8s/app-deployment-new.yaml;
      cat k8s/app-deployment-new.yaml;

# deploying k8s
- id: Deploying k8s
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/app-deployment-new.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1' # nome do cluster